# Generated by Django 5.2 on 2025-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OfferPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
