# Generated by Django 5.0.7 on 2025-04-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titlepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Description', models.TextField()),
            ],
        ),
    ]
