# Generated by Django 5.2 on 2025-05-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_categories_product_about_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Sidebarimage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Sidebarimage2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Sidebarimage3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
