# Generated by Django 5.2 on 2025-05-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0005_product_image2_product_image3_product_sidebarimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='About',
            field=models.TextField(default=''),
        ),
    ]
