# Generated by Django 5.2 on 2025-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0006_alter_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='AvailableQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='StockStatus',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
