# Generated by Django 5.2 on 2025-05-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0008_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textapp.brands'),
        ),
    ]
