# Generated by Django 5.2 on 2025-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0013_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlepage',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
