# Generated by Django 5.2 on 2025-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0018_orderitem_price_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
