# Generated by Django 5.2 on 2025-05-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0019_orderitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
