# Generated by Django 5.2 on 2025-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0020_order_ordered_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryandCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image3',
        ),
    ]
